import { RedirectToSignIn, SignedOut } from '@clerk/nextjs'

import Footer from './footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <div>{children}</div>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
      <Footer className='fixed h-24 bg-blue-200 bottom-0 w-full left-0 right-0 rounded-t-xl shadow dark:bg-gray-800' />
    </>
  )
}
