import Navbar from 'components/navbar'

import '../assets/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='flex min-h-screen overflow-x-hidden flex-col bg-white'>
        <Navbar />
        <main className='left-0 right-0 flex-grow py-4 mb-24 mt-24'>
          {children}
        </main>
      </body>
    </html>
  )
}
