type RawExercise = {
  name: string
  description: string
}

export const exercisesArray = [
  { name: 'Ab Wheel' },
  { name: 'Alternating DB Press' },
  { name: 'Alternating Hammer Curl' },
  { name: 'Ankle and Big Toe Dorsiflexion' },
  { name: '1-Arm Cable Rows' },
  { name: '1-Arm Lat Pull Downs' },
  { name: '1-Arm Tricep Pushdown' },
  { name: 'Back Raise' },
  { name: 'Band Good Mornings' },
  { name: 'Band Pullaparts' },
  { name: 'Band Pullover Dead Bugs' },
  { name: 'Barbell Curls' },
  { name: 'Barbell Hip Thrust' },
  { name: 'Barbell Russian Twists' },
  { name: 'Barbell Shrugs' },
  { name: 'Barbell Skullcrushers' },
  { name: 'Bayesian Bicep Curl' },
  { name: 'Bear Crawl Rock Backs' },
  { name: 'Bear Crawl Shoulder Touch' },
  { name: 'Belt Squat' },
  { name: 'Bent Knee Calf Raises' },
  { name: 'Bentover Rows' },
  { name: 'Bird Dogs' },
  { name: '2" Block Pull' },
  { name: 'Block Pull' },
  { name: 'Box Deadlift' },
  { name: 'Box Jumps' },
  { name: 'Box Pushups' },
  { name: 'Box Squat' },
  { name: 'Bradford Presses' },
  { name: '90/90 Breathing' },
  { name: 'Cable Cross Overs' },
  { name: 'Cable Curl' },
  { name: 'Cable Fly' },
  { name: 'Cable Hercules Curls' },
  { name: 'Cable Rope Curl' },
  { name: 'Calf Raises' },
  { name: 'Cambered Bar Bench' },
  { name: 'Chest Supported Rows' },
  { name: 'Chin-ups' },
  { name: 'Chinup Grip Pulldowns' },
  { name: 'Clapping pushup' },
  { name: 'Close Grip Slingshot' },
  { name: 'Closegrip Bench' },
  { name: 'Closegrip Pushup' },
  { name: 'Comp Bench' },
  { name: 'Comp Deadlift' },
  { name: 'Comp Squat' },
  { name: 'Concentration Curls' },
  { name: '3" Conv Block Pull' },
  { name: '1" Conv Deficit Deadlift' },
  { name: 'Conventional Deadlift' },
  { name: 'Conventional Deadlift (Tech)' },
  { name: 'Conventional Deadlift Touch n Go w/ straps' },
  { name: 'Couch Stretch' },
  { name: '5 Count Pause Bench' },
  { name: '3 Count Pause Bench' },
  { name: 'DB Alternating Curls' },
  { name: 'DB Arnold Press' },
  { name: 'DB Bench' },
  { name: 'DB Bench w/ Deep Stretch' },
  { name: 'DB Cuban Press' },
  { name: 'DB Curls' },
  { name: 'DB Drag Curls' },
  { name: 'DB Floor Press' },
  { name: 'DB Fly' },
  { name: 'DB Front Raise' },
  { name: 'DB Incline Bench' },
  { name: 'DB Jumps' },
  { name: 'DB Lateral Raise' },
  { name: 'DB Military Press' },
  { name: 'DB Pinwheel Curls' },
  { name: 'DB Pull Overs' },
  { name: 'DB RDLs' },
  { name: 'DB Rear Delt Fly' },
  { name: 'DB Rows' },
  { name: 'DB Shrugs' },
  { name: 'Dead Bugs' },
  { name: 'Dead Squat' },
  { name: 'Decline Push-ups' },
  { name: 'Deficit DB RDL' },
  { name: 'Depth Jumps' },
  { name: 'Depth Pushups' },
  { name: 'Diamond Pushups' },
  { name: 'Dicks Press' },
  { name: 'Dips' },
  { name: 'Double Overhand 1" Conv Deficit Deadlift' },
  { name: 'Drag Curls' },
  { name: 'Drop Pushups' },
  { name: 'Elbows Out DB Extensions' },
  { name: 'Extra Wide Bench Press' },
  { name: 'EZ Bar Curls' },
  { name: 'Face Pulls' },
  { name: 'Farmers Walk' },
  { name: 'Feet Up Bench' },
  { name: 'Floor Press' },
  { name: 'Front Foot Elevated Split Squat' },
  { name: 'Front Plank' },
  { name: 'Front Plank w/ Band Row' },
  { name: 'Front Squat' },
  { name: 'GHR' },
  { name: 'Glute Bridge' },
  { name: 'Goblet Pause Squat' },
  { name: 'Goblet Squat' },
  { name: 'Good Mornings' },
  { name: 'Hack Squat' },
  { name: 'Halting Conventional Deadlift' },
  { name: 'Halting Sumo Deadlift' },
  { name: 'Hammer Curls' },
  { name: 'Hamstring Curls' },
  { name: 'Hand Switch Pushups' },
  { name: 'Hanging Leg Raises' },
  { name: 'High Bar Squat' },
  { name: 'High Isometric Conventional Deadlift' },
  { name: 'High Isometric Sumo Deadlift' },
  { name: 'High Pin Press' },
  { name: 'Hollow Body Hold' },
  { name: 'Incline Bench' },
  { name: 'Incline DB Curl' },
  { name: 'Incline DB Fly' },
  { name: 'Incline Hammer Curl' },
  { name: 'Inverted Rows' },
  { name: 'Iso Hold DB Lateral Raises' },
  { name: 'Iso Hold Hammer Curls' },
  { name: 'Iso Hold Pushups' },
  { name: 'JM Press' },
  { name: 'Keg Carry' },
  { name: 'Kettlebell Swing' },
  { name: 'Lat Pulldowns' },
  { name: 'Lateral Lunges' },
  { name: 'Leg Extensions' },
  { name: 'Leg Press/Hack Squat' },
  { name: 'Low Bar Squat' },
  { name: 'Low Box Squat' },
  { name: 'Low Isometric Conventional Deadlift' },
  { name: 'Low Isometric Sumo Deadlift' },
  { name: 'Low Pin Press' },
  { name: 'Lunges' },
  { name: 'Lying Leg Curl' },
  { name: 'Machine Assisted Nordic Ham' },
  { name: 'Machine Chest Press' },
  { name: 'Machine Curl' },
  { name: 'Machine Hip Abduction' },
  { name: 'Machine Hip Thrust' },
  { name: 'Machine Lateral Raise' },
  { name: 'Machine Military Press' },
  { name: 'Machine Rear Delt Fly' },
  { name: 'Machine Shoulder Press' },
  { name: 'Machine Situp' },
  { name: 'Machine-Assisted Nordic Ham Raise' },
  { name: 'MB Russian Twists' },
  { name: 'Military Press' },
  { name: 'Military Push-ups' },
  { name: 'Neutral Grip Chinups' },
  { name: 'Neutral Grip Pulldowns' },
  { name: 'Neutral Grip Pushup' },
  { name: 'Overhead Cable Tricep Extension' },
  { name: 'Overhead DB Extensions' },
  { name: 'Overhead Dicks Press' },
  { name: 'Pallof Press' },
  { name: 'Pause Above the Knee Conv Deadlift' },
  { name: 'Pause Above the Knee Sumo Deadlift' },
  { name: 'Pause Below the Knee Conv Deadlift' },
  { name: 'Pause Below the Knee Sumo Deadlift' },
  { name: 'Pause Front Squat' },
  { name: 'Pause High Bar Squat' },
  { name: 'Pause Leg Press/Hack Squat' },
  { name: 'Pause Off the Floor Conv Deadlift' },
  { name: 'Pause Off the Floor Sumo Deadlift' },
  { name: 'Pause Squat' },
  { name: 'Pause Squat (Halfway Down)' },
  { name: 'Pause Squat (Halfway Up)' },
  { name: 'Paused At Knee Sumo Deadlift' },
  { name: 'Pec Deck' },
  { name: 'Pendlay Row' },
  { name: 'Pendulum Squat' },
  { name: 'Plate Front Raises' },
  { name: 'Plate Front Raises with Twist' },
  { name: 'Plyo Push-up' },
  { name: 'Preacher Curls' },
  { name: 'Pull Throughs' },
  { name: 'Pullups' },
  { name: 'Push Press' },
  { name: 'Pushups w/ Deep Stretch' },
  { name: 'RDL w/ Band Around Hips' },
  { name: 'RDLs' },
  { name: 'Rear Foot Elevated Split Squat' },
  { name: 'Reverse Band Bench' },
  { name: 'Reverse Band Conv Deadlift' },
  { name: 'Reverse Band Deadlift' },
  { name: 'Reverse Band Squat' },
  { name: 'Reverse Band Sumo Deadlift' },
  { name: 'Reverse Grip Tricep Pushdown' },
  { name: 'Reverse Hack Squat' },
  { name: 'Reverse Hyper' },
  { name: 'Rolling Tricep Extensions' },
  { name: 'SA Farmers Walk' },
  { name: 'Sandbag Carry' },
  { name: 'Seal Rows' },
  { name: 'Seated DB Military Press' },
  { name: 'Seated Military Press' },
  { name: 'Seated Rows' },
  { name: 'Shrugs' },
  { name: 'Side Plank' },
  { name: 'Side Plank w/ Rotation' },
  { name: 'Single Leg Calf Raises' },
  { name: 'Single Leg Reverse Hyper' },
  { name: 'Single-Arm Cable Curl' },
  { name: 'Skullcrusher' },
  { name: 'Skullcrushers (Standing)' },
  { name: 'SL Glute Bridge' },
  { name: 'SL Hip Thrust' },
  { name: 'SL Leg Press/Hack Squat' },
  { name: 'Slingshot Bench' },
  { name: 'Snatch Grip RDL' },
  { name: 'Snatch Grip Tempo Deadlifts (4:0:4)' },
  { name: 'Snatch-Grip Deadlift' },
  { name: 'Special Bicep Lat Pulldown' },
  { name: 'Split Squat (Glute Emphasis)' },
  { name: 'Split Squat (Quad Emphasis)' },
  { name: 'Spoto Press' },
  { name: 'Squat Jump' },
  { name: 'Squat Morning' },
  { name: 'SSB Squat' },
  { name: 'Staggered RDL w/ Pause' },
  { name: 'Staggered Stance RDLs' },
  { name: 'Step Ups' },
  { name: '3" Sumo Block Pull' },
  { name: 'Sumo Deadlift' },
  { name: 'Sumo Deadlift (Tech)' },
  { name: 'Sumo Deadlift Touch n Go w/ straps' },
  { name: '1" Sumo Deficit Deadlift' },
  { name: 'Sumo Stance RDL' },
  { name: 'Tall Kneeling Glute Activation' },
  { name: 'Tempo DB Press (5:0:5)' },
  { name: 'Tempo High Bar Squat (5:0:0)' },
  { name: 'Tempo Squat (5:0:0)' },
  { name: 'Tempo Stiff Leg Deadlift (5:0:0)' },
  { name: 'Tempo Wide Grip Bench (5:0:0)' },
  { name: 'Trap Bar Deadlift' },
  { name: 'Tricep Kick Back' },
  { name: 'Tricep Pushdown' },
  { name: 'Tricep Rope Extensions' },
  { name: 'TRX IYT' },
  { name: 'Underhand Grip Chest Supported Rows' },
  { name: 'Underhand Grip Seal Rows' },
  { name: 'Underhand Lat Machine Row' },
  { name: 'Upper Back Cat/Cow' },
  { name: 'Upright Rows' },
  { name: 'V-Ups' },
  { name: 'Weighted Situps' },
  { name: 'Wide Grip Seated Row' },
  { name: 'Yates Rows' },
  { name: 'Yoke Walk' },
  { name: 'Zottman Curls' },
]
