type RawExercise = {
  name: string
  description: string
}

export const exercisesArray = [
  { id: 1, name: 'Ab Wheel', equipment: 'other' },
  { id: 2, name: 'Alternating DB Press', equipment: 'dumbbell' },
  { id: 3, name: 'Alternating Hammer Curl', equipment: 'dumbbell' },
  { id: 4, name: 'Ankle and Big Toe Dorsiflexion', equipment: 'other' },
  { id: 5, name: '1-Arm Cable Rows', equipment: 'cable' },
  { id: 6, name: '1-Arm Lat Pull Downs', equipment: 'cable' },
  { id: 7, name: '1-Arm Tricep Pushdown', equipment: 'cable' },
  { id: 8, name: 'Back Raise', equipment: 'bodyweight' },
  { id: 9, name: 'Band Good Mornings', equipment: 'band' },
  { id: 10, name: 'Band Pullaparts', equipment: 'band' },
  { id: 11, name: 'Band Pullover Dead Bugs', equipment: 'band' },
  { id: 12, name: 'Barbell Curls', equipment: 'barbell' },
  { id: 13, name: 'Barbell Hip Thrust', equipment: 'barbell' },
  { id: 14, name: 'Barbell Russian Twists', equipment: 'barbell' },
  { id: 15, name: 'Barbell Shrugs', equipment: 'barbell' },
  { id: 16, name: 'Barbell Skullcrushers', equipment: 'barbell' },
  { id: 17, name: 'Bayesian Bicep Curl', equipment: 'barbell' },
  { id: 18, name: 'Bear Crawl Rock Backs', equipment: 'bodyweight' },
  { id: 19, name: 'Bear Crawl Shoulder Touch', equipment: 'bodyweight' },
  { id: 20, name: 'Belt Squat', equipment: 'other' },
  { id: 21, name: 'Bent Knee Calf Raises', equipment: 'bodyweight' },
  { id: 22, name: 'Bentover Rows', equipment: 'barbell' },
  { id: 23, name: 'Bird Dogs', equipment: 'bodyweight' },
  { id: 24, name: '2" Block Pull', equipment: 'barbell' },
  { id: 25, name: 'Block Pull', equipment: 'barbell' },
  { id: 26, name: 'Box Deadlift', equipment: 'barbell' },
  { id: 27, name: 'Box Jumps', equipment: 'bodyweight' },
  { id: 28, name: 'Box Pushups', equipment: 'bodyweight' },
  { id: 29, name: 'Box Squat', equipment: 'barbell' },
  { id: 30, name: 'Bradford Presses', equipment: 'barbell' },
  { id: 31, name: '90/90 Breathing', equipment: 'bodyweight' },
  { id: 32, name: 'Cable Cross Overs', equipment: 'cable' },
  { id: 33, name: 'Cable Curl', equipment: 'cable' },
  { id: 34, name: 'Cable Fly', equipment: 'cable' },
  { id: 35, name: 'Cable Hercules Curls', equipment: 'cable' },
  { id: 36, name: 'Cable Rope Curl', equipment: 'cable' },
  { id: 37, name: 'Calf Raises', equipment: 'bodyweight' },
  { id: 38, name: 'Cambered Bar Bench', equipment: 'barbell' },
  { id: 39, name: 'Chest Supported Rows', equipment: 'machine' },
  { id: 40, name: 'Chin-ups', equipment: 'bodyweight' },
  { id: 41, name: 'Chinup Grip Pulldowns', equipment: 'cable' },
  { id: 42, name: 'Clapping pushup', equipment: 'bodyweight' },
  { id: 43, name: 'Close Grip Slingshot', equipment: 'barbell' },
  { id: 44, name: 'Closegrip Bench', equipment: 'barbell' },
  { id: 45, name: 'Closegrip Pushup', equipment: 'bodyweight' },
  { id: 46, name: 'Comp Bench', equipment: 'barbell' },
  { id: 47, name: 'Comp Deadlift', equipment: 'barbell' },
  { id: 48, name: 'Comp Squat', equipment: 'barbell' },
  { id: 49, name: 'Concentration Curls', equipment: 'dumbbell' },
  { id: 50, name: '3" Conv Block Pull', equipment: 'barbell' },
  { id: 51, name: '1" Conv Deficit Deadlift', equipment: 'barbell' },
  { id: 52, name: 'Conventional Deadlift', equipment: 'barbell' },
  { id: 53, name: 'Conventional Deadlift (Tech)', equipment: 'barbell' },
  {
    id: 54,
    name: 'Conventional Deadlift Touch n Go w/ straps',
    equipment: 'barbell',
  },
  { id: 55, name: 'Couch Stretch', equipment: 'other' },
  { id: 56, name: '5 Count Pause Bench', equipment: 'barbell' },
  { id: 57, name: '3 Count Pause Bench', equipment: 'barbell' },
  { id: 58, name: 'DB Alternating Curls', equipment: 'dumbbell' },
  { id: 59, name: 'DB Arnold Press', equipment: 'dumbbell' },
  { id: 60, name: 'DB Bench', equipment: 'dumbbell' },
  { id: 61, name: 'DB Bench w/ Deep Stretch', equipment: 'dumbbell' },
  { id: 62, name: 'DB Cuban Press', equipment: 'dumbbell' },
  { id: 63, name: 'DB Curls', equipment: 'dumbbell' },
  { id: 64, name: 'DB Drag Curls', equipment: 'dumbbell' },
  { id: 65, name: 'DB Floor Press', equipment: 'dumbbell' },
  { id: 66, name: 'DB Fly', equipment: 'dumbbell' },
  { id: 67, name: 'DB Front Raise', equipment: 'dumbbell' },
  { id: 68, name: 'DB Incline Bench', equipment: 'dumbbell' },
  { id: 69, name: 'DB Jumps', equipment: 'dumbbell' },
  { id: 70, name: 'DB Lateral Raise', equipment: 'dumbbell' },
  { id: 71, name: 'DB Military Press', equipment: 'dumbbell' },
  { id: 72, name: 'DB Pinwheel Curls', equipment: 'dumbbell' },
  { id: 73, name: 'DB Pull Overs', equipment: 'dumbbell' },
  { id: 74, name: 'DB RDLs', equipment: 'dumbbell' },
  { id: 75, name: 'DB Rear Delt Fly', equipment: 'dumbbell' },
  { id: 76, name: 'DB Rows', equipment: 'dumbbell' },
  { id: 77, name: 'DB Shrugs', equipment: 'dumbbell' },
  { id: 78, name: 'Dead Bugs', equipment: 'bodyweight' },
  { id: 79, name: 'Dead Squat', equipment: 'barbell' },
  { id: 80, name: 'Decline Push-ups', equipment: 'bodyweight' },
  { id: 81, name: 'Deficit DB RDL', equipment: 'dumbbell' },
  { id: 82, name: 'Depth Jumps', equipment: 'bodyweight' },
  { id: 83, name: 'Depth Pushups', equipment: 'bodyweight' },
  { id: 84, name: 'Diamond Pushups', equipment: 'bodyweight' },
  { id: 85, name: 'Dicks Press', equipment: 'barbell' },
  { id: 86, name: 'Dips', equipment: 'bodyweight' },
  {
    id: 87,
    name: 'Double Overhand 1" Conv Deficit Deadlift',
    equipment: 'barbell',
  },
  { id: 88, name: 'Drag Curls', equipment: 'barbell' },
  { id: 89, name: 'Drop Pushups', equipment: 'bodyweight' },
  { id: 90, name: 'Elbows Out DB Extensions', equipment: 'dumbbell' },
  { id: 91, name: 'Extra Wide Bench Press', equipment: 'barbell' },
  { id: 92, name: 'EZ Bar Curls', equipment: 'barbell' },
  { id: 93, name: 'Face Pulls', equipment: 'cable' },
  { id: 94, name: 'Farmers Walk', equipment: 'other' },
  { id: 95, name: 'Feet Up Bench', equipment: 'barbell' },
  { id: 96, name: 'Floor Press', equipment: 'barbell' },
  { id: 97, name: 'Front Foot Elevated Split Squat', equipment: 'barbell' },
  { id: 98, name: 'Front Plank', equipment: 'bodyweight' },
  { id: 99, name: 'Front Plank w/ Band Row', equipment: 'bodyweight' },
  { id: 100, name: 'Front Squat', equipment: 'barbell' },
  { id: 101, name: 'GHR', equipment: 'bodyweight' },
  { id: 102, name: 'Glute Bridge', equipment: 'bodyweight' },
  { id: 103, name: 'Goblet Pause Squat', equipment: 'dumbbell' },
  { id: 104, name: 'Goblet Squat', equipment: 'dumbbell' },
  { id: 105, name: 'Good Mornings', equipment: 'barbell' },
  { id: 106, name: 'Hack Squat', equipment: 'machine' },
  { id: 107, name: 'Halting Conventional Deadlift', equipment: 'barbell' },
  { id: 108, name: 'Halting Sumo Deadlift', equipment: 'barbell' },
  { id: 109, name: 'Hammer Curls', equipment: 'dumbbell' },
  { id: 110, name: 'Hamstring Curls', equipment: 'machine' },
  { id: 111, name: 'Hand Switch Pushups', equipment: 'bodyweight' },
  { id: 112, name: 'Hanging Leg Raises', equipment: 'bodyweight' },
  { id: 113, name: 'High Bar Squat', equipment: 'barbell' },
  {
    id: 114,
    name: 'High Isometric Conventional Deadlift',
    equipment: 'barbell',
  },
  { id: 115, name: 'High Isometric Sumo Deadlift', equipment: 'barbell' },
  { id: 116, name: 'High Pin Press', equipment: 'barbell' },
  { id: 117, name: 'Hollow Body Hold', equipment: 'bodyweight' },
  { id: 118, name: 'Incline Bench', equipment: 'barbell' },
  { id: 119, name: 'Incline DB Curl', equipment: 'dumbbell' },
  { id: 120, name: 'Incline DB Fly', equipment: 'dumbbell' },
  { id: 121, name: 'Incline Hammer Curl', equipment: 'dumbbell' },
  { id: 122, name: 'Inverted Rows', equipment: 'bodyweight' },
  { id: 123, name: 'Iso Hold DB Lateral Raises', equipment: 'dumbbell' },
  { id: 124, name: 'Iso Hold Hammer Curls', equipment: 'dumbbell' },
  { id: 125, name: 'Iso Hold Pushups', equipment: 'bodyweight' },
  { id: 126, name: 'JM Press', equipment: 'barbell' },
  { id: 127, name: 'Keg Carry', equipment: 'other' },
  { id: 128, name: 'Kettlebell Swing', equipment: 'other' },
  { id: 129, name: 'Lat Pulldowns', equipment: 'cable' },
  { id: 130, name: 'Lateral Lunges', equipment: 'bodyweight' },
  { id: 131, name: 'Leg Extensions', equipment: 'machine' },
  { id: 132, name: 'Leg Press/Hack Squat', equipment: 'machine' },
  { id: 133, name: 'Low Bar Squat', equipment: 'barbell' },
  { id: 134, name: 'Low Box Squat', equipment: 'barbell' },
  {
    id: 135,
    name: 'Low Isometric Conventional Deadlift',
    equipment: 'barbell',
  },
  { id: 136, name: 'Low Isometric Sumo Deadlift', equipment: 'barbell' },
  { id: 137, name: 'Low Pin Press', equipment: 'barbell' },
  { id: 138, name: 'Lunges', equipment: 'dumbbell' },
  { id: 139, name: 'Lying Leg Curl', equipment: 'machine' },
  { id: 140, name: 'Machine Assisted Nordic Ham', equipment: 'machine' },
  { id: 141, name: 'Machine Chest Press', equipment: 'machine' },
  { id: 142, name: 'Machine Curl', equipment: 'machine' },
  { id: 143, name: 'Machine Hip Abduction', equipment: 'machine' },
  { id: 144, name: 'Machine Hip Thrust', equipment: 'machine' },
  { id: 145, name: 'Machine Lateral Raise', equipment: 'machine' },
  { id: 146, name: 'Machine Military Press', equipment: 'machine' },
  { id: 147, name: 'Machine Rear Delt Fly', equipment: 'machine' },
  { id: 148, name: 'Machine Shoulder Press', equipment: 'machine' },
  { id: 149, name: 'Machine Situp', equipment: 'machine' },
  { id: 150, name: 'Machine-Assisted Nordic Ham Raise', equipment: 'machine' },
  { id: 151, name: 'MB Russian Twists', equipment: 'other' },
  { id: 152, name: 'Military Press', equipment: 'barbell' },
  { id: 153, name: 'Military Push-ups', equipment: 'bodyweight' },
  { id: 154, name: 'Neutral Grip Chinups', equipment: 'bodyweight' },
  { id: 155, name: 'Neutral Grip Pulldowns', equipment: 'cable' },
  { id: 156, name: 'Neutral Grip Pushup', equipment: 'bodyweight' },
  { id: 157, name: 'Overhead Cable Tricep Extension', equipment: 'cable' },
  { id: 158, name: 'Overhead DB Extensions', equipment: 'dumbbell' },
  { id: 159, name: 'Overhead Dicks Press', equipment: 'barbell' },
  { id: 160, name: 'Pallof Press', equipment: 'cable' },
  { id: 161, name: 'Pause Above the Knee Conv Deadlift', equipment: 'barbell' },
  { id: 162, name: 'Pause Above the Knee Sumo Deadlift', equipment: 'barbell' },
  { id: 163, name: 'Pause Below the Knee Conv Deadlift', equipment: 'barbell' },
  { id: 164, name: 'Pause Below the Knee Sumo Deadlift', equipment: 'barbell' },
  { id: 165, name: 'Pause Front Squat', equipment: 'barbell' },
  { id: 166, name: 'Pause High Bar Squat', equipment: 'barbell' },
  { id: 167, name: 'Pause Leg Press/Hack Squat', equipment: 'machine' },
  { id: 168, name: 'Pause Off the Floor Conv Deadlift', equipment: 'barbell' },
  { id: 169, name: 'Pause Off the Floor Sumo Deadlift', equipment: 'barbell' },
  { id: 170, name: 'Pause Squat', equipment: 'barbell' },
  { id: 171, name: 'Pause Squat (Halfway Down)', equipment: 'barbell' },
  { id: 172, name: 'Pause Squat (Halfway Up)', equipment: 'barbell' },
  { id: 173, name: 'Paused At Knee Sumo Deadlift', equipment: 'barbell' },
  { id: 174, name: 'Pec Deck', equipment: 'machine' },
  { id: 175, name: 'Pendlay Row', equipment: 'barbell' },
  { id: 176, name: 'Pendulum Squat', equipment: 'machine' },
  { id: 177, name: 'Plate Front Raises', equipment: 'other' },
  { id: 178, name: 'Plate Front Raises with Twist', equipment: 'other' },
  { id: 179, name: 'Plyo Push-up', equipment: 'bodyweight' },
  { id: 180, name: 'Preacher Curls', equipment: 'barbell' },
  { id: 181, name: 'Pull Throughs', equipment: 'cable' },
  { id: 182, name: 'Pullups', equipment: 'bodyweight' },
  { id: 183, name: 'Push Press', equipment: 'barbell' },
  { id: 184, name: 'Pushups w/ Deep Stretch', equipment: 'bodyweight' },
  { id: 185, name: 'RDL w/ Band Around Hips', equipment: 'barbell' },
  { id: 186, name: 'RDLs', equipment: 'barbell' },
  { id: 187, name: 'Rear Foot Elevated Split Squat', equipment: 'dumbbell' },
  { id: 188, name: 'Reverse Band Bench', equipment: 'barbell' },
  { id: 189, name: 'Reverse Band Conv Deadlift', equipment: 'barbell' },
  { id: 190, name: 'Reverse Band Deadlift', equipment: 'barbell' },
  { id: 191, name: 'Reverse Band Squat', equipment: 'barbell' },
  { id: 192, name: 'Reverse Band Sumo Deadlift', equipment: 'barbell' },
  { id: 193, name: 'Reverse Grip Tricep Pushdown', equipment: 'cable' },
  { id: 194, name: 'Reverse Hack Squat', equipment: 'machine' },
  { id: 195, name: 'Reverse Hyper', equipment: 'machine' },
  { id: 196, name: 'Rolling Tricep Extensions', equipment: 'dumbbell' },
  { id: 197, name: 'SA Farmers Walk', equipment: 'dumbbell' },
  { id: 198, name: 'Sandbag Carry', equipment: 'other' },
  { id: 199, name: 'Seal Rows', equipment: 'barbell' },
  { id: 200, name: 'Seated DB Military Press', equipment: 'dumbbell' },
  { id: 201, name: 'Seated Military Press', equipment: 'barbell' },
  { id: 202, name: 'Seated Rows', equipment: 'cable' },
  { id: 203, name: 'Shrugs', equipment: 'barbell' },
  { id: 204, name: 'Side Plank', equipment: 'bodyweight' },
  { id: 205, name: 'Side Plank w/ Rotation', equipment: 'bodyweight' },
  { id: 206, name: 'Single Leg Calf Raises', equipment: 'bodyweight' },
  { id: 207, name: 'Single Leg Reverse Hyper', equipment: 'machine' },
  { id: 208, name: 'Single-Arm Cable Curl', equipment: 'cable' },
  { id: 209, name: 'Skullcrusher', equipment: 'barbell' },
  { id: 210, name: 'Skullcrushers (Standing)', equipment: 'barbell' },
  { id: 211, name: 'SL Glute Bridge', equipment: 'bodyweight' },
  { id: 212, name: 'SL Hip Thrust', equipment: 'bodyweight' },
  { id: 213, name: 'SL Leg Press/Hack Squat', equipment: 'machine' },
  { id: 214, name: 'Slingshot Bench', equipment: 'barbell' },
  { id: 215, name: 'Snatch Grip RDL', equipment: 'barbell' },
  {
    id: 216,
    name: 'Snatch Grip Tempo Deadlifts (4:0:4)',
    equipment: 'barbell',
  },
  { id: 217, name: 'Snatch-Grip Deadlift', equipment: 'barbell' },
  { id: 218, name: 'Special Bicep Lat Pulldown', equipment: 'cable' },
  { id: 219, name: 'Split Squat (Glute Emphasis)', equipment: 'dumbbell' },
  { id: 220, name: 'Split Squat (Quad Emphasis)', equipment: 'dumbbell' },
  { id: 221, name: 'Spoto Press', equipment: 'barbell' },
  { id: 222, name: 'Squat Jump', equipment: 'bodyweight' },
  { id: 223, name: 'Squat Morning', equipment: 'barbell' },
  { id: 224, name: 'SSB Squat', equipment: 'barbell' },
  { id: 225, name: 'Staggered RDL w/ Pause', equipment: 'dumbbell' },
  { id: 226, name: 'Staggered Stance RDLs', equipment: 'dumbbell' },
  { id: 227, name: 'Step Ups', equipment: 'bodyweight' },
  { id: 228, name: '3" Sumo Block Pull', equipment: 'barbell' },
  { id: 229, name: 'Sumo Deadlift', equipment: 'barbell' },
  { id: 230, name: 'Sumo Deadlift (Tech)', equipment: 'barbell' },
  { id: 231, name: 'Sumo Deadlift Touch n Go w/ straps', equipment: 'barbell' },
  { id: 232, name: '1" Sumo Deficit Deadlift', equipment: 'barbell' },
  { id: 233, name: 'Sumo Stance RDL', equipment: 'dumbbell' },
  { id: 234, name: 'Tall Kneeling Glute Activation', equipment: 'bodyweight' },
  { id: 235, name: 'Tempo DB Press (5:0:5)', equipment: 'dumbbell' },
  { id: 236, name: 'Tempo High Bar Squat (5:0:0)', equipment: 'barbell' },
  { id: 237, name: 'Tempo Squat (5:0:0)', equipment: 'barbell' },
  { id: 238, name: 'Tempo Stiff Leg Deadlift (5:0:0)', equipment: 'barbell' },
  { id: 239, name: 'Tempo Wide Grip Bench (5:0:0)', equipment: 'barbell' },
  { id: 240, name: 'Trap Bar Deadlift', equipment: 'barbell' },
  { id: 241, name: 'Tricep Kick Back', equipment: 'dumbbell' },
  { id: 242, name: 'Tricep Pushdown', equipment: 'cable' },
  { id: 243, name: 'Tricep Rope Extensions', equipment: 'cable' },
  { id: 244, name: 'TRX IYT', equipment: 'bodyweight' },
  { id: 245, name: 'Underhand Grip Chest Supported Rows', equipment: 'cable' },
  { id: 246, name: 'Underhand Grip Seal Rows', equipment: 'barbell' },
  { id: 247, name: 'Underhand Lat Machine Row', equipment: 'cable' },
  { id: 248, name: 'Upper Back Cat/Cow', equipment: 'bodyweight' },
  { id: 249, name: 'Upright Rows', equipment: 'barbell' },
  { id: 250, name: 'V-Ups', equipment: 'bodyweight' },
  { id: 251, name: 'Weighted Situps', equipment: 'bodyweight' },
  { id: 252, name: 'Wide Grip Seated Row', equipment: 'cable' },
  { id: 253, name: 'Yates Rows', equipment: 'barbell' },
  { id: 254, name: 'Yoke Walk', equipment: 'other' },
  { id: 255, name: 'Zottman Curls', equipment: 'dumbbell' },
]
